In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

This project is called MUSHROOM PROJECT. This project is to determine whether the mushroom edible or poisonous. This project aim to find the most effective algorithm or machine learning model to do the task above.

#Data Loading

In [ ]:
#definisikan nama kolom dataframe
name_list=['Class','cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment',
           'gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring',
           'stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type',
           'veil-color','ring-number','ring-type','spore-print-color','population','habitat']

In [ ]:
# from google.colab import files
# uploaded=files.upload()

In [ ]:
#import dataset dari website
#silahkan jika menggunakan nama variable yang berbeda

# jamur=pd.read_csv("iris.csv",names=name_list)
jamur=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data",names=name_list)

In [ ]:
jamur

Class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

#Data sanity check

In [ ]:
## apakah ada "missing value" ?
## jawaban : tidak ada 
# jamur.isnull().sum()
#jamur.info()

In [ ]:
## balance / unbalance ?
# jawaban : balance karena persen minority classnya lebih besar dari 40 % , minority class disini merupakan huruf p
# jamur['Class'].value_counts()

# tidak perlu oversampling
# df['sex'].value_counts()

e    4208
p    3916
Name: Class, dtype: int64

Apakah menurut anda proses *oversampling* perlu dilakukan ?  

#Data Training Construction

In [ ]:
#encode dataset dari panda ke numpy
from sklearn.preprocessing import LabelEncoder
number = LabelEncoder()
label= number.fit_transform(jamur['Class'])#.astype('str'))
jamur['cap-shape']= number.fit_transform(jamur['cap-shape'])#.astype('str'))
jamur['cap-surface']= number.fit_transform(jamur['cap-surface'])#.astype('str'))
jamur['cap-color']= number.fit_transform(jamur['cap-color'])#.astype('str'))
jamur['bruises']= number.fit_transform(jamur['bruises'])#.astype('str'))
jamur['odor']= number.fit_transform(jamur['odor'])#.astype('str'))
jamur['gill-attachment']= number.fit_transform(jamur['gill-attachment'])#.astype('str'))
jamur['gill-spacing']= number.fit_transform(jamur['gill-spacing'])#.astype('str'))
jamur['gill-size']= number.fit_transform(jamur['gill-size'])#.astype('str'))
jamur['gill-color']= number.fit_transform(jamur['gill-color'])#.astype('str'))
jamur['stalk-shape']= number.fit_transform(jamur['stalk-shape'])#.astype('str'))
jamur['stalk-root']= number.fit_transform(jamur['stalk-root'])#.astype('str'))
jamur['stalk-surface-above-ring']= number.fit_transform(jamur['stalk-surface-above-ring'])#.astype('str'))
jamur['stalk-surface-below-ring']= number.fit_transform(jamur['stalk-surface-below-ring'])#.astype('str'))
jamur['stalk-color-above-ring']= number.fit_transform(jamur['stalk-color-above-ring'])#.astype('str'))
jamur['stalk-color-below-ring']= number.fit_transform(jamur['stalk-color-below-ring'])#.astype('str'))
jamur['veil-type']= number.fit_transform(jamur['veil-type'])#.astype('str'))
jamur['veil-color']= number.fit_transform(jamur['veil-color'])#.astype('str'))
jamur['ring-number']= number.fit_transform(jamur['ring-number'])#.astype('str'))
jamur['ring-type']= number.fit_transform(jamur['ring-type'])#.astype('str'))
jamur['spore-print-color']= number.fit_transform(jamur['spore-print-color'])#.astype('str'))
jamur['population']= number.fit_transform(jamur['population'])#.astype('str'))
jamur['habitat']= number.fit_transform(jamur['habitat'])#.astype('str'))

# jamur.tail(5)
# arr =jamur.to_Numpy()
# print(" Dataframe types ",arr)
jamur[['Class','cap-shape','cap-surface','cap-color','bruises','odor','gill-attachment',
           'gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring',
           'stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type',
           'veil-color','ring-number','ring-type','spore-print-color','population','habitat']].to_numpy()
# pd.DataFrame({"A": [1, 2], "B": [3, 4]}).to_numpy()
#jangan lupa melakukan Label Encoding (https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

array([[1, 5, 2, ..., 2, 3, 5],
       [0, 5, 2, ..., 3, 2, 1],
       [0, 0, 2, ..., 3, 2, 3],
       ...,
       [0, 2, 2, ..., 0, 1, 2],
       [1, 3, 3, ..., 7, 4, 2],
       [0, 5, 2, ..., 4, 1, 2]])

In [ ]:
print(label)
dadu =number.inverse_transform(label)
print(dadu)

[1 0 0 ... 0 1 0]
[1 0 0 ... 0 1 0]


In [ ]:
# jangan lupa, split data untuk melakukan cross validation
from sklearn.model_selection import train_test_split
X= jamur.values[:,1:23]
Y= jamur.values[:,0]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.1, random_state=100)

# http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html#sklearn.model_selection.cross_val_score

#Training Methods

Berikut ini adalah evaluasi dari berbagai methoda yang digunakan.

##Naive Bayes

In [1]:
# https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB
# https://www.datacamp.com/community/tutorials/naive-bayes-scikit-learn

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
y_pred = gnb.predict(X_test)

NameError: ignored

In [ ]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy:", metrics.accuracy_score(Y_test, y_pred)*100)


jangan lupa melakukan analisis

##kNN

In [ ]:
#sudah pernah dibahas di pertemuan kelas
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=11, p=2,metric='euclidean')

In [ ]:
classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

In [ ]:
 #Y_test

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
cm = confusion_matrix(Y_test, y_pred)
print (cm)
print(f1_score(Y_test, y_pred))

[[427   0]
 [  0 386]]
1.0


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test, y_pred)*100)

100.0


##SVM (Support Vector Machine)

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='linear') # Linear Kernel
clf.fit(X_train, Y_train)
y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred)*100)

Accuracy: 99.0159901599016


In [ ]:
print("Precision:",metrics.precision_score(Y_test, y_pred))
print("Recall:",metrics.recall_score(Y_test, y_pred))

Precision: 0.9846153846153847
Recall: 0.9948186528497409


##Decision Tree 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf_entropy= DecisionTreeClassifier(criterion= 'entropy', random_state=100, 
  max_depth= 3 , min_samples_leaf=5)
clf_entropy.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [ ]:
y_pred_en= clf_entropy.predict(X_test)
y_pred_en = number.inverse_transform(jamur['Class'])
y_pred_en
# df = pd.DataFrame(y_pred_en)
# print(df)

array(['g', 'd', 'd', ..., 'd', 'g', 'd'], dtype=object)

In [ ]:
Y_test= number.inverse_transform(jamur['Class'])
Y_test

array(['g', 'd', 'd', ..., 'd', 'g', 'd'], dtype=object)

In [ ]:
# plt.xlabel('Real')
# plt.ylabel('Prediction')
# # plt.scatter(X_train, Y_train,color='g')
# plt.scatter(Y_test,y_pred_en, color='b')

In [ ]:
from sklearn.metrics import accuracy_score
print(" Accuracy is" , accuracy_score(Y_test,y_pred_en)*100)

 Accuracy is 94.7109471094711


##Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
clf.predict(X_test)

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

In [ ]:
# clf.predict_proba(X_test)[0:10]
# Y_test

In [ ]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(Y_test, y_pred)*100)


Accuracy: 99.0159901599016


#Pembahasan

Analisa Machine Learning :

Metode yang kurang baik untuk mengklasifikasi data ini adalah KNN dengan akurasi 100 % karena terjadi overfitting. Overfitting menyebabkan timbulnya noise pada data. 
Akurasi Random Forest sebesar 99% juga lebih baik daripada Desicion Tree dengan 94%. Hal ini wajar dikarenakan random forest adalah kumpulan desicion tree sehingga akurasi akan lebih akurat. Random forest memiliki akurasi yang tinggi karena dapat mengurangi overfitting. Naive bayes menjadi metode yang memiliki akurasi yang paling rendah di antara metode lainnya yaitu sebesar 91%. Akurasi Naive bayes diukur menggunakan probabilitas. SVM memiliki akurasi 99 % dan dataset dapat diklasifikasi dengan baik dengan menggunakan metode ini. SVM mencari hyperplane dengan margin terbesar. Hal ini menyebabkan, SVM dapat mengkontrol akurasi.

#Kesimpulan

SVM dan Random Forest adalah metode terbaik untuk mengklasifikasi dataset jamur. KNN adalah metode yang kurang baik untuk mengklasifikasi dataset jamur.

